### ISSUE TITLE
giga brain solution (python)

### ISSUE THREAD

**Issue by blackwidoq** [jeffrylew/add-wrinkles-to-brain#2]
https://www.hackerrank.com/challenges/balanced-brackets/forum/comments/800459

**Comment by jeffrylew** [comment]
I just realized I did this one [recently](https://github.com/jeffrylew/add-wrinkles-to-brain/blob/main/cpp/stacks_and_queues/balanced_brackets.cpp).

I saw the giga brain solution, pretty smart. Unfortunately, it is much easier to code the giga brain solution in Python than C++
